layout_spectrum: 0.5974383966200569
typography_spectrum: 0.4856426505797939
color:
  saturation: 0.06260420502762835
  brandStrength: 0.4642898854065576
  lightness: 0.11122746343650662
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.204012354863992
title: Practical Acts
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/59890dd2-409b-4c1b-bf78-153a6eba69e4.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/59890dd2-409b-4c1b-bf78-153a6eba69e4.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
purpose:
  - type: external
    url: 'https://twitter.com/PracticalActs'
    label: Twitter
  - type: email
    url: 'mailto:info@practicalacts.org'
    label: Contact us
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: 'Thinking, Tinkering, Leading Transformation'
navigation:
  - name: About
    id: f76018f7-0e17-4dee-aa96-21a3dcd5cfc4
    type: content
  - name: LinkedIn
    url: 'https://uk.linkedin.com/in/stuartmills'
    type: external
analytics:
  google: UA-90484664-1
name: PracticalActs
author:
  email: stuart@practicalacts.org
url: 'http://www.practicalacts.org'
github: true
