layout_spectrum: 0.024776504430182204
typography_spectrum: 0.9610105459766444
color:
  saturation: 0.5628429807043902
  brandStrength: 0.9874854767627755
  lightness: 0.6760976342307312
  brandColors:
    - '#FFFEDF'
    - '#10110D'
    - '#313534'
    - '#8E9569'
    - '#53663F'
  rhythmicContrast: 0.12591342329822186
title: Practical Acts
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ed3b7d1d-cc70-42c7-8c76-e509f58cbd29.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ed3b7d1d-cc70-42c7-8c76-e509f58cbd29.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
purpose:
  - type: external
    url: 'https://twitter.com/PracticalActs'
    label: Twitter
  - type: email
    url: 'mailto:info@practicalacts.org'
    label: Contact us
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: 'Thinking, Tinkering, Leading Transformation'
navigation:
  - name: About
    id: f76018f7-0e17-4dee-aa96-21a3dcd5cfc4
    type: content
  - name: LinkedIn
    url: 'https://uk.linkedin.com/in/stuartmills'
    type: external
analytics:
  google: UA-90484664-1
name: PracticalActs
author:
  email: stuart@practicalacts.org
url: 'http://www.practicalacts.org'
github: true
