layout_spectrum: 0.3858797202972087
typography_spectrum: 0.08218607284276203
color:
  saturation: 0.3633364311197201
  brandStrength: 0.6273705980286813
  lightness: 0.9456695771440494
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.7888237132300798
title: Practical Acts
content: []
purpose:
  - type: external
    url: 'https://twitter.com/PracticalActs'
    label: Twitter
  - type: email
    url: 'mailto:info@practicalacts.org'
    label: Contact us
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: 'Thinking, Tinkering, Leading Transformation'
navigation:
  - name: About
    id: f76018f7-0e17-4dee-aa96-21a3dcd5cfc4
    type: content
  - name: LinkedIn
    url: 'https://uk.linkedin.com/in/stuartmills'
    type: external
analytics:
  google: UA-90484664-1
name: PracticalActs
author:
  email: stuart@practicalacts.org
url: 'http://www.practicalacts.org'
github: true
